export interface Institution {
  code: string;
  name: string;
  nameFr: string;
  address: string;
  city: string;
  province: string;
  postalCode: string;
  atipEmail?: string;
  phone?: string;
  fax?: string;
}

export const INSTITUTIONS: Record<string, Institution> = {
  DFO: {
    code: "DFO",
    name: "Fisheries and Oceans Canada",
    nameFr: "Pêches et Océans Canada",
    address: "ATIP Coordinator, 200 Kent Street",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0E6",
    phone: "613-993-0999",
  },
  DND: {
    code: "DND",
    name: "National Defence",
    nameFr: "Défense nationale",
    address: "Director Access to Information and Privacy, 101 Colonel By Drive",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0K2",
    phone: "613-996-2353",
  },
  ESDC: {
    code: "ESDC",
    name: "Employment and Social Development Canada",
    nameFr: "Emploi et Développement social Canada",
    address: "ATIP Division, 140 Promenade du Portage, Phase IV",
    city: "Gatineau",
    province: "QC",
    postalCode: "K1A 0J9",
    phone: "819-654-6949",
  },
  FCAC: {
    code: "FCAC",
    name: "Financial Consumer Agency of Canada",
    nameFr: "Agence de la consommation en matière financière du Canada",
    address: "ATIP Coordinator, 427 Laurier Avenue West",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1R 1B9",
  },
  GAC: {
    code: "GAC",
    name: "Global Affairs Canada",
    nameFr: "Affaires mondiales Canada",
    address: "ATIP Division, 125 Sussex Drive",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0G2",
    phone: "343-203-5963",
  },
  HC: {
    code: "HC",
    name: "Health Canada",
    nameFr: "Santé Canada",
    address: "ATIP Coordinator, Address Locator 0900C2, 70 Colombine Driveway",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0K9",
    phone: "613-954-9165",
  },
  INFC: {
    code: "INFC",
    name: "Infrastructure Canada",
    nameFr: "Infrastructure Canada",
    address: "ATIP Coordinator, 180 Kent Street",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1P 0B6",
  },
  IRCC: {
    code: "IRCC",
    name: "Immigration, Refugees and Citizenship Canada",
    nameFr: "Immigration, Réfugiés et Citoyenneté Canada",
    address: "ATIP, 180 Kent Street",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 1L1",
    phone: "613-954-1064",
  },
  NRC: {
    code: "NRC",
    name: "National Research Council Canada",
    nameFr: "Conseil national de recherches Canada",
    address: "ATIP Coordinator, 1200 Montreal Road",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0R6",
    phone: "613-993-9101",
  },
  NRCAN: {
    code: "NRCAN",
    name: "Natural Resources Canada",
    nameFr: "Ressources naturelles Canada",
    address: "ATIP Division, 580 Booth Street",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0E4",
    phone: "343-292-6070",
  },
  PCO: {
    code: "PCO",
    name: "Privy Council Office",
    nameFr: "Bureau du Conseil privé",
    address: "ATIP Coordinator, 85 Sparks Street",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0A3",
    phone: "613-957-5153",
  },
  PMO: {
    code: "PMO",
    name: "Prime Minister's Office",
    nameFr: "Cabinet du Premier ministre",
    address: "ATIP Coordinator, Langevin Block, 80 Wellington Street",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0A2",
  },
  PS: {
    code: "PS",
    name: "Public Safety Canada",
    nameFr: "Sécurité publique Canada",
    address: "ATIP Division, 269 Laurier Avenue West",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0P8",
    phone: "613-944-4875",
  },
  PSPC: {
    code: "PSPC",
    name: "Public Services and Procurement Canada",
    nameFr: "Services publics et Approvisionnement Canada",
    address: "ATIP Division, Place du Portage, Phase III, 11 Laurier Street",
    city: "Gatineau",
    province: "QC",
    postalCode: "K1A 0S5",
    phone: "819-956-3136",
  },
  RCMP: {
    code: "RCMP",
    name: "Royal Canadian Mounted Police",
    nameFr: "Gendarmerie royale du Canada",
    address: "ATIP Branch, 73 Leikin Drive",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0R2",
    phone: "613-825-1002",
  },
  SSC: {
    code: "SSC",
    name: "Shared Services Canada",
    nameFr: "Services partagés Canada",
    address: "ATIP Coordinator, 180 Kent Street",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1P 0B6",
    phone: "613-219-0401",
  },
  TC: {
    code: "TC",
    name: "Transport Canada",
    nameFr: "Transports Canada",
    address: "ATIP Division, 330 Sparks Street",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0N5",
    phone: "613-990-2309",
  },
  TBS: {
    code: "TBS",
    name: "Treasury Board of Canada Secretariat",
    nameFr: "Secrétariat du Conseil du Trésor du Canada",
    address: "ATIP Division, 90 Elgin Street",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0R5",
    phone: "613-369-3200",
  },
  VAC: {
    code: "VAC",
    name: "Veterans Affairs Canada",
    nameFr: "Anciens Combattants Canada",
    address: "ATIP Unit, 66 Slater Street",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0P4",
    phone: "902-566-8397",
  },
  CRA: {
    code: "CRA",
    name: "Canada Revenue Agency",
    nameFr: "Agence du revenu du Canada",
    address: "Access to Information and Privacy Directorate, 555 MacKenzie Avenue",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0L5",
    phone: "613-952-0306",
  },
  CBSA: {
    code: "CBSA",
    name: "Canada Border Services Agency",
    nameFr: "Agence des services frontaliers du Canada",
    address: "ATIP Division, 191 Laurier Avenue West",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0L8",
    phone: "613-952-0304",
  },
  CSE: {
    code: "CSE",
    name: "Communications Security Establishment",
    nameFr: "Centre de la sécurité des télécommunications",
    address: "ATIP Coordinator, PO Box 9703 Terminal",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1G 3Z4",
  },
  CSIS: {
    code: "CSIS",
    name: "Canadian Security Intelligence Service",
    nameFr: "Service canadien du renseignement de sécurité",
    address: "ATIP Coordinator, PO Box 9732 Terminal",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1G 4G4",
    phone: "613-993-9620",
  },
  PHAC: {
    code: "PHAC",
    name: "Public Health Agency of Canada",
    nameFr: "Agence de la santé publique du Canada",
    address: "ATIP Division, 130 Colonnade Road",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0K9",
    phone: "613-954-5995",
  },
  ISED: {
    code: "ISED",
    name: "Innovation, Science and Economic Development Canada",
    nameFr: "Innovation, Sciences et Développement économique Canada",
    address: "ATIP Division, 235 Queen Street",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0H5",
    phone: "343-291-1220",
  },
  ENV: {
    code: "ENV",
    name: "Environment and Climate Change Canada",
    nameFr: "Environnement et Changement climatique Canada",
    address: "ATIP Division, 351 Saint-Joseph Boulevard",
    city: "Gatineau",
    province: "QC",
    postalCode: "K1A 0H3",
    phone: "819-938-4215",
  },
  FIN: {
    code: "FIN",
    name: "Finance Canada",
    nameFr: "Finances Canada",
    address: "ATIP Division, 90 Elgin Street",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0G5",
    phone: "613-369-4009",
  },
  JUS: {
    code: "JUS",
    name: "Justice Canada",
    nameFr: "Justice Canada",
    address: "ATIP Unit, 284 Wellington Street",
    city: "Ottawa",
    province: "ON",
    postalCode: "K1A 0H8",
    phone: "613-941-2522",
  },
};

export function getInstitutionByName(name: string): Institution | undefined {
  const normalized = name.toLowerCase();
  return Object.values(INSTITUTIONS).find(
    (inst) =>
      inst.name.toLowerCase().includes(normalized) ||
      inst.nameFr.toLowerCase().includes(normalized) ||
      inst.code.toLowerCase() === normalized
  );
}

export function getInstitutionFullAddress(institution: Institution): string {
  return `${institution.address}\n${institution.city}, ${institution.province}  ${institution.postalCode}`;
}
