-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Proposed ATIP requests generated by AI
create table if not exists proposed_requests (
  id uuid primary key default uuid_generate_v4(),
  created_at timestamptz default now(),
  institution text not null,
  institution_code text,
  description text not null,
  date_range text,
  ai_reasoning text,
  source_type text default 'csv' check (source_type in ('csv', 'press_release')),
  status text default 'pending' check (status in ('pending', 'approved', 'rejected', 'archived')),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id),
  edited_description text,
  batch_date date default current_date
);

-- Approved and submitted requests with PDF tracking
create table if not exists submitted_requests (
  id uuid primary key default uuid_generate_v4(),
  created_at timestamptz default now(),
  proposed_request_id uuid references proposed_requests(id) on delete cascade,
  institution text not null,
  description text not null,
  tracking_number text,
  submitted_at timestamptz,
  status text default 'approved' check (status in ('approved', 'submitted', 'received', 'completed')),
  notes text,
  pdf_url text,
  user_id uuid references auth.users(id)
);

-- ATIP voluntary disclosures cache
create table if not exists atip_disclosures (
  id uuid primary key default uuid_generate_v4(),
  created_at timestamptz default now(),
  atip_number text unique,
  institution text not null,
  institution_code text,
  summary text not null,
  url text,
  pages integer,
  released_date date,
  ai_headline text,
  cached_at timestamptz default now()
);

-- Generated news stories from disclosures
create table if not exists generated_stories (
  id uuid primary key default uuid_generate_v4(),
  created_at timestamptz default now(),
  disclosure_id uuid references atip_disclosures(id) on delete cascade,
  story_text text not null,
  questions text,
  user_id uuid references auth.users(id)
);

-- API request logs for rate limiting
create table if not exists api_logs (
  id uuid primary key default uuid_generate_v4(),
  created_at timestamptz default now(),
  user_id uuid references auth.users(id),
  endpoint text not null,
  ip_address text,
  success boolean default true
);

-- RLS Policies
alter table proposed_requests enable row level security;
alter table submitted_requests enable row level security;
alter table atip_disclosures enable row level security;
alter table generated_stories enable row level security;
alter table api_logs enable row level security;

-- Authenticated users can read all proposed requests
create policy "Auth users can read proposed_requests"
  on proposed_requests for select
  to authenticated
  using (true);

-- Authenticated users can update proposed requests (approve/reject/archive)
create policy "Auth users can update proposed_requests"
  on proposed_requests for update
  to authenticated
  using (true);

-- Service role can insert proposed requests (from cron)
create policy "Service role can insert proposed_requests"
  on proposed_requests for insert
  to service_role
  with check (true);

-- Submitted requests policies
create policy "Auth users can read own submitted_requests"
  on submitted_requests for select
  to authenticated
  using (user_id = auth.uid());

create policy "Auth users can insert submitted_requests"
  on submitted_requests for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "Auth users can update own submitted_requests"
  on submitted_requests for update
  to authenticated
  using (user_id = auth.uid());

-- ATIP disclosures are public read
create policy "Anyone can read atip_disclosures"
  on atip_disclosures for select
  to authenticated
  using (true);

create policy "Service role can manage atip_disclosures"
  on atip_disclosures for all
  to service_role
  using (true);

-- Generated stories
create policy "Auth users can manage own stories"
  on generated_stories for all
  to authenticated
  using (user_id = auth.uid());

-- API logs
create policy "Auth users can read own logs"
  on api_logs for select
  to authenticated
  using (user_id = auth.uid());

create policy "Auth users can insert logs"
  on api_logs for insert
  to authenticated
  with check (user_id = auth.uid());

-- Indexes for performance
create index if not exists idx_proposed_requests_status on proposed_requests(status);
create index if not exists idx_proposed_requests_batch_date on proposed_requests(batch_date);
create index if not exists idx_proposed_requests_institution on proposed_requests(institution);
create index if not exists idx_atip_disclosures_released_date on atip_disclosures(released_date desc);
create index if not exists idx_submitted_requests_user_id on submitted_requests(user_id);
